custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/button.py
custom_components/solax_modbus/const.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/select.py
custom_components/solax_modbus/sensor.py

Some examples in const.py have already been introduced.
The __init__.py still contains a block of code that needs to be removed once the config dialog has been simplfied and the serial number decoding is complete
Attention: this is hardly tested (tested on gen4 x3)

Prepare for deriving max_current from serial number prefix, introduce blacklist based on SN prefix

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/const.py

Attention: AC model still under development !
factoryname and modulename removed

Correction for AC model , small enhancements

---

custom_components/solax_modbus/__init__.py

Meter/CT should now also work for AC model, dont read non-existing registers on AC
Slight enhancements for readability 
(yes, it becomes messy, sorry, feel free to reject this PR )

AC model: Adapt read-only sensors according to manual 

---

custom_components/solax_modbus/const.py

Dont know when this was introduced
I believed I corrected this, but the error re-appeared

re-correct HYB-GROUP-BITS

---

custom_components/solax_modbus/const.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/sensor.py

First used on export_control_user_limit (correct issue  #58 on gen4 with wrong  scaling)
https://github.com/wills106/homeassistant-solax-modbus/issues/58
Similar mechanism as used for the max_current
Hopefully this does not break other things ...

Introduce scaling for sensors and numbers and fix isssue #58

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/button.py

Just a suggestion for MIC, feel free to solve it differently (see @kars remarks)
Correct button indentation error

Correct sleeping MIC behaviour, correct button indentation error

---

custom_components/solax_modbus/__init__.py

correct typo in last change for MIC - sorry

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/const.py

Change total_yield to kWh instead of MWh
Correct MIC sleep mode according to inputs from @Kars

change total_yield to kWh instead of MWh - correct MIC sleep mode

---

custom_components/solax_modbus/__init__.py

Correct error introduced this morning. Sorry, I was not awake ...

correct MIC sleep / awake mode

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/sensor.py

This new function is not yet called ...

adding just an initial draft for the new read_xxx_registers_all function

---

custom_components/solax_modbus/const.py
custom_components/solax_modbus/plugin_sofar.py
custom_components/solax_modbus/plugin_solax.py
custom_components/solax_modbus/select.py

make select options compatible with upcoming 2022.11 release

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/plugin_solax.py

might help to resolve problems mentioned in converfsation #173 by  @raenji-sk

enhance fault handling for easier debugging

---

custom_components/solax_modbus/__init__.py

the old method did not seem to correspond to the pymodbus docs
Unsure if this will work better ...

try to enhance error logging

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/button.py
custom_components/solax_modbus/plugin_solax.py

Be aware that I cannot test this for the time being.
Only plugin_solax has been updated. If we want similar feature for the other brands, we should give these plugins the optional isAwake() and wakeupButton() functions

Implement feature request #226: automatic awake

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/button.py

Correct error in auto-wakeup

---

custom_components/solax_modbus/__init__.py

As I currently cannot test write actions, could you please test a write action, to make sure I did not break normal write operations
Thanks

auto-wakeup: avoid endless self-call

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/button.py
custom_components/solax_modbus/const.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/plugin_sofar.py
custom_components/solax_modbus/plugin_sofar_old.py
custom_components/solax_modbus/plugin_solax.py
custom_components/solax_modbus/plugin_solis.py
custom_components/solax_modbus/plugin_solis_old.py
custom_components/solax_modbus/select.py
custom_components/solax_modbus/sensor.py

Just for your testing as I did a simplification of the endian approach.
It is now on plugin level and no longer on entity level.

Intermediate sync - some preparations before implementing write_multiple

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/button.py
custom_components/solax_modbus/config_flow.py
custom_components/solax_modbus/const.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/plugin_solax.py
custom_components/solax_modbus/select.py
custom_components/solax_modbus/sensor.py

Also: allow partial reconfiguration of integration

First version with Gen4 remote power control - probably still immature

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/plugin_solax.py

Also remove non-implemented options

Introduce remotecontrol "grid control"  option (active power - house load ) (Gen4)

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/select.py

Config entry update according to suggestion from @gelse
If initvalue attribute of number or select entities is None, it will not appear in the datadict anymore.
This makes it possible to specify another default in the value_function

Enhance config_entry update, make initvalue optional attribute

---

custom_components/solax_modbus/plugin_solis.py

Fixes https://github.com/wills106/homeassistant-solax-modbus/issues/307#issuecomment-1475333256

fix incorrect bms battery current scale

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/const.py
custom_components/solax_modbus/sensor.py

set to True to prevent updates (except when RO modbus value changes)
See also #295 (comment)

implement prevent_update attribute for sensors

---

custom_components/solax_modbus/plugin_solis.py

Fixes https://github.com/wills106/homeassistant-solax-modbus/issues/406

Update plugin_solis.py to remove scale from House Load Total

---

custom_components/solax_modbus/plugin_solax.py

Add unit_of_measurement for EPS Mode Runtime

---

custom_components/solax_modbus/const.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/plugin_solax.py
custom_components/solax_modbus/sensor.py

Might solve [[BUG] solax_export_control_user_limit entities incorrect by 10x](https://github.com/wills106/homeassistant-solax-modbus/issues/418#top)
#418

simplify read_scale mechanis - adapt export_control_user_limit scale exception for some models

---

.github/workflows/hacs.yml

It will perform some basic checks to be sure we comply with hacs repo rules.

Add hacs GitHub action

---

.github/FUNDING.yml

It needs to be enabled in repository settings too.

Add file for GitHub sponsor button

---

README.md

Refactor of README.md

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/non_solax_inverter.yaml
.github/ISSUE_TEMPLATE/solax.yml

Since there are only a few options, it might be more comfortable to have a list of them. Also in my opinion labels should be lowercase, changing them is still an option, because they do not exist yet, thus no duplication.

Use dropdown menu for plugins in bug templates

---

custom_components/solax_modbus/plugin_solis.py

Adds some Modes to the Solis Energy Control Switch that were missing

Solis modes

---

custom_components/solax_modbus/plugin_solax.py

Disable sensor entities that have a control entity

---

custom_components/solax_modbus/plugin_solax.py

Disable remaining sensors with controls

---

docs/solax-faq.md

Might help to prevent <https://github.com/wills106/homeassistant-solax-modbus/discussions/604> in future again.

Add a note about master-slave to faq

---

docs/faq.md

- Use proper component name
- Fix regex syntax

Update FAQ information regarding "Blocking call" warning

---

custom_components/solax_modbus/plugin_sofar.py

Add ZP2 serial for Azzurro ZSS inverter

Add ZP2 serial for Azzurro ZSS inverter to plugin_sofar.py

---

docs/sofar-installation.md
docs/sofar-operation-modes.md

Added documentation about Sofar Modes of operations also as follow up to #748.
Added resistor termination to RS485 installation.

Documentation: Added Sofar modes of operations and RS485 termination

---

docs/sofar-installation.md

Better documentation on how to connect the terminator resistor on Sofar inverters

Doc: Better connection of Sofar terminator

---

custom_components/solax_modbus/plugin_sofar.py

Fixed typo in entity name

---

custom_components/solax_modbus/const.py

Fixes #815 by checking that `sync_rtc_offset` returns a number

Fix RTC Sync Bug

---

docs/solis-operation-modes.md

Provide more info to users based on feedback received in:
https://github.com/wills106/homeassistant-solax-modbus/pull/795

Add a description for Energy Storage Control Switch

---

custom_components/solax_modbus/__init__.py

Should resolve  #816 
I moved all locks down to self._client....
Checked and remove possible deadlocks.
Tests are good, but if it was deadlock problem it is really hard to test. Please report all problems.

Reduce locking to minimum scope (Modbus client only)

---

docs/sofar-faq.md

Updated FAQ regarding firmware issues with RS485 communication

Sofar: Updated FAQ about frequent RS485 hangs.

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/plugin_growatt.py
custom_components/solax_modbus/plugin_sofar.py
custom_components/solax_modbus/plugin_sofar_old.py
custom_components/solax_modbus/plugin_solax.py
custom_components/solax_modbus/plugin_solax_a1j1.py
custom_components/solax_modbus/plugin_solinteg.py
custom_components/solax_modbus/plugin_solis.py
custom_components/solax_modbus/plugin_solis_old.py
custom_components/solax_modbus/plugin_srne.py
custom_components/solax_modbus/plugin_swatten.py

Waits for the inverter if Modbus communication is disrupted when Homeassistant is started

Wait for determine inverter type

---

custom_components/solax_modbus/__init__.py

Close #937
Wrap ConnectionException and ModbusIOException in a HomeAssistantError

Fix #937: Automations stop and ignore 'continue_on_error': Thrown ModbusIOException not handled and converted to HomeAssistantError

---

custom_components/solax_modbus/__init__.py

moved blocking file operations into async executor job

---

custom_components/solax_modbus/__init__.py

Fix for #948 - HA deprecation warnings

Fix HA deprecated calls

---

custom_components/solax_modbus/plugin_sofar_old.py

Tested on an AZZURRO 1PH 3000TL-V3: everything seems to work just fine.

Add AZZURRO 1PH 3000-6000-V1 as sofar_old

---

custom_components/solax_modbus/plugin_solinteg.py

solinteg: fix initialization + other small

---

custom_components/solax_modbus/plugin_solinteg.py

meter_2_measured_power (not existing) in value_function_house_load creates glitches...

fix House Load glitches

---

custom_components/solax_modbus/plugin_growatt.py

Fixes https://github.com/wills106/homeassistant-solax-modbus/issues/979

Remove GEN3 from Inverter State and Run Mode

---

custom_components/solax_modbus/plugin_solax.py

864 - fix EPS yeild total for GEN4 - scale

---

custom_components/solax_modbus/__init__.py

https://github.com/wills106/homeassistant-solax-modbus/issues/980

fix voltage and frequency showing unknown

---

custom_components/solax_modbus/config_flow.py

Adding serial inverters was not possible for me without this change

Fix support-battery error for serial inverters #976

---

custom_components/solax_modbus/plugin_solinteg.py

I did NOT realize that data is NOT hub.data inside scale function...

fix individual MPPT shadow scan

---

custom_components/solax_modbus/plugin_solax.py

Reverts wills106/homeassistant-solax-modbus#1082
Messes up Gen3

Revert "Solax Gen4 meter direction and core meter direction fix"

---

custom_components/solax_modbus/plugin_solax.py

I have two inverters with this serial. After the change the component works well for me.

Add X3 MIC 8kW serial number

---

custom_components/solax_modbus/plugin_solinteg.py

adjust some register limits
add "Battery Protection Relax" register
migrate to software/hardware _version

small updates for Solinteg plugin

---

docs/compatible-adaptors.md

Update compatible-adaptors.md - added Wifi - RS485 option

---

custom_components/solax_modbus/plugin_solinteg.py

add new inverter modes (PeakShift, Feed-In, TuU-no time window yet)
subtract backup power from house load
Off-grid control buttons

Solinteg updates

---

custom_components/solax_modbus/translations/nl.json

Updated dutch translation in translations/nl.json based on missing entries in translation/en.json

Update nl translation

---

custom_components/solax_modbus/plugin_sofar.py

Fix #1320: Max and min cell voltages are swapped

---

custom_components/solax_modbus/plugin_sofar_old.py

Fix #1280 HYD3600ES Wrong inverter type is being detected

---

custom_components/solax_modbus/__init__.py

In last fix I forget to do it for holding registers

Fix No transactionID for holding registers

---

custom_components/solax_modbus/plugin_solis_fb00.py

Fix register to update discharge slot 6 for Solis-FB00

Fix register to update discharge slot 6 for Solis-FB00

---

custom_components/solax_modbus/plugin_solax.py

I have tested this on my own inverter and it works well.

Add X1-IES 3.7kW

---

docs/installation.md
docs/modbus-adaptor-setup.md
docs/solax-G4-operation-modes.md
docs/solax-entity-description.md

I have improved the documentation especially regarding Solax.

Doc update

---

custom_components/solax_modbus/plugin_growatt.py

Growatt GEN4
Merge part of @flopp999 large PR #1338 to fix issues #1401 and remove duplicate register #1405 
It uses "value_function_module_status" in scale which can handle unknowns. All from @flopp999's PR

Growatt - Fix #1401, #1405, #1415

---

custom_components/solax_modbus/plugin_growatt.py

Added Time 4-9
some typos
Big change for function "value_function_time_slot_1", old function renamed for safety "value_function_time_slot_1_old"

Update plugin_growatt.py timer 4-9

---

LICENSE

Missing copyright information in license

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/select.py
custom_components/solax_modbus/sensor.py
docs/developer_guide.md

remove callbacks for select and number entities
remove some heavy debug outputs

enhance debugging output; rename entity_group to scan_group

---

docs/compatible-adaptors.md

I added support for the ESP8266 and Arduino framework.

ESP8266 support added to ESPHome modbus bridge adapter

---

custom_components/solax_modbus/switch.py

correct part of issue #1546

---

custom_components/solax_modbus/button.py
custom_components/solax_modbus/const.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/select.py
custom_components/solax_modbus/switch.py

sofar: implement depends_on for button, numberer, switch,  select also

---

custom_components/solax_modbus/pymodbus_compat.py

I'm running it on pymodbus 3.9.2 on my productive instance and it works.
I tested the file locally and it seems it works on 3.6.7, 3.7.4, 3.9.2 and 3.11.1.
This is the simple test I performed.
```
python3 -c "import pymodbus_compat as pc; print(pc.pymodbus_version_info())"
python3 - <<'EOF'
import pymodbus_compat as pc
from pymodbus_compat import DataType
regs = pc.convert_to_registers('ZP1E', DataType.STRING, 'big')
print('regs:', regs)
print('decoded:', pc.convert_from_registers(regs, DataType.STRING, 'big'))
EOF
```
Result:
```
pymodbus version 3.6.7, new api loaded: True
regs: [23120, 12613]
decoded: ZP1E
```

pymodbus compat layer changes to make it work

---

custom_components/solax_modbus/__init__.py
custom_components/solax_modbus/number.py
custom_components/solax_modbus/plugin_solax.py
custom_components/solax_modbus/sensor.py

related to export_control_user_limit scaling
unrelated: also solves bug  #1624 for Pro models

re-implement read_scale so that datadict already contains correctly scaled values
