wills106/homeassistant-solax-modbus

- solax_modbus/const.py
Hi, this is a simple PR for fixing a small typo in Battery Discharge Max Current.
Btw, many thanks for the integration you created. I spent many hours establishing a reliable connection between Solax, Eastron smart meter and Home assistant via RS485 to TCP bridge. Your solution is much better than all my experients.
> Fix typo in Battery Discharge Max Current

- solax_modbus/__init__.py
This PR fixes the inverter power scale for each phase.
Values for:
- Inverter Power R (register address 0x6C or 108)
- Inverter Power S
- Inverter Power T
loaded from Modbus registers are in Watts and should not be scaled by 0.1.
After this fix the formula `Inverter power R + S +T =  Inverter Power` is valid 
(`grid_power_r + grid_power_s + grid_power_t = inverter_load`).
This PR has been tested on SolaX Hybrid X3.
> Fix Inverter power scale for each phase

- solax_modbus/__init__.py
I found a mistake in run mode. When run mode code == 3, then the inverter is Off.
Number 3 is the correct value for Feedin Priority work mode (Charger Use Mode), not for inverter status.
The screenshot shows the wrong run mode when I switched the inverter off.
> Fix run mode code for Off mode + fix typo

- custom_components/solax_modbus/const.py
Use mode dropdown did not correctly show current settting in  feedin mode
This problem/change only applies to the Gen4 systems
> Correct use mode dropdown for feed-in mosz

- README.md
- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/const.py
Added 23:59 time to the time tables, as this is the default discharge_end_time (on gen4).
Some Gen4 parameters were not displayed correctly in their select dropdown.
I also corrected some typos in the Gen4 discharge time windows.
I also removed an unused Gen4 declaration.
> Some Gen4 corrections (related  to time windows)

- custom_components/solax_modbus/const.py
bitmask for the group was wrong
> Correct typo: faulty recognition of HYBRID or AC

- custom_components/solax_modbus/plugin_sofar.py
Heatsink Temperature 1 is supported on my PV device, therefore add PV to the allowedtypes
> Add PV to Heatsink Temperature 1

- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/const.py
A failing block read will be accepted as valid block if the first entity of the block contains a non-False ignore_readerror attribute. The other entitties of the block can also have an ignore_readerror attribute that determines the value returned upon failure.
Typically, this attribute is set to "Unknown" or None
Untested for the time being
> introduce ignore_readerror attribute for sensor entities (untested)

- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/const.py
- custom_components/solax_modbus/number.py
- custom_components/solax_modbus/plugin_solax.py
- custom_components/solax_modbus/sensor.py
Use case: WRITE_LOCAL_DATA number with same key as modbus sensor entity Local_data changes will be memorized for 120 seconds, awaiting a write_multiple action
> re-implement prevent_update

- custom_components/solax_modbus/plugin_growatt.py
I enabled EPS and got errors in the log :
```
2023-08-20 15:14:03.086 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state
numerical_value = int(value)
^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '50Hz'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/solax_modbus/__init__.py", line 292, in async_refresh_modbus_data
update_callback()
File "/config/custom_components/solax_modbus/sensor.py", line 172, in _modbus_data_updated
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in …
```
> Remove Hz from frequency

- custom_components/solax_modbus/plugin_growatt.py
When using a widget showing power flow, the separate charge/discharge power is a bit clunky. So combined them. Also made the battery power sensors have more appropriate icons.
> Create a combined battery charge power sensor. (for Growatt)

- custom_components/solax_modbus/translations/de.json
Fixed some typos in German language.
Shortened an overflowing message:
> Fixed typos. Shorted overflowing message

- custom_components/solax_modbus/__init__.py
I have a Sofar hyd 15ktl-3ph and Waveshare RS485 to RJ45 Ethernet in use.
Occasionally I get "read failed at ..." errors (especially when the polling frequency for modubus registers is set to 15 seconds or lower).
This PR does not solve the cause, but the consequence errors!
In case of a failed communication (**read failed at ... 0x{descr.register:02x} ...**), **val = 0** was set.
This caused the long term statistics for entities with **state_class** = **total_increasing** to get messed up.
Statistics->**Sum** was calculated incorrectly. 
The result was that the energy dashboard was also always messed up.
The return value **None** now ensures that HA receives the value **Unknown** and no longer falsifies the **Sum**.
> Fixed Long term statistics in error case

- custom_components/solax_modbus/plugin_solax.py
It's called GMPPT on newer firmwares and solar fix on older ones. Did not change entity id, so it does not break any existing automations.
> Update solax solar fix entity name

- .github/ISSUE_TEMPLATE/config.yml
People that do not understand GitHub flow and will try to open an issue for a question that is not directly related to this extensions will be prompted to use discussions.
> Add a link to discussions when creating a new issue

- custom_components/solax_modbus/const.py
When the inverter is switched on, but the system is turned off and the battery is switched off as well, the plugin would run into several `KeyException`'s. This change is fixing these by providing default values.
> Avoid KeyException

- .github/ISSUE_TEMPLATE/solax.yml
Forms provide richer experience over templates. They are easier to fill by users, can provide them more information and will force them to fill required information. Tags need to be created in order to be applied. My vision is to have per brand issue form, so it can be tailored exactly, but that's just my point of view and I could provide a generic one instead.
> Add SolaX bug form

- custom_components/solax_modbus/plugin_solax.py
Adds support for an AC only variant of the X3 Hybrid G4.
> Add X3 Hybrid G4 FIT variant

- custom_components/solax_modbus/plugin_solax_ev_charger.py
Initialization failed for one user because of missing flags.
ALL_PM_GROUP
This is simple fix, better will be to remove the flags from EV Changer completely as there is no reason for it.
> Fix missing flags

- custom_components/solax_modbus/plugin_sofar_old.py
SA3 series are part of SOFAR 1.1K...3.3KTL-G3 product lineup.
> Add Sofar SA3 series inverter support

- custom_components/solax_modbus/select.py
Looks like select wasn't updated and all "select" entities ended up in a different device in 2024.02.3
> Fix select device issue

- custom_components/solax_modbus/plugin_sofar.py
When setting battery power, desired grid was always set to 0 and battery min and max charge to the value of passive_mode_battery_power. This does not allow the full flexibility of the passive mode
With this addition users can set desired grid power, minimum charge/discharge and maximum charge/discharge:
When setting these values the registers are set accordingly:
Now this allows finer control like this:
- Passive Mode Grid Power: 0
- Passive Mode Max Battery Power: 2500
- Passive Mode Min Battery Power: -5000
Try to keep grid power at zero like in self use, but limit charging of the battery to 2.5kW, while still allowing discharging to 5 kW
- Passive Mode Grid Power: 2000
- Passive Mode Max Battery Power: 5000
- Passive Mode Min Battery Power: 0
Force charging the battery with 2 kW while …
> Allow to set desired grid power along with minimum and maximum battery power.

- custom_components/solax_modbus/plugin_sofar.py
Renamed labels of Sofar Inverter entities as suggested in #747
> Renaming Sofar labels as suggested in #747

- custom_components/solax_modbus/plugin_sofar.py
- docs/sofar-entity-description.md
Update System Time wasn't working previously. The write action needs to write 7 registers, where the last register will be a 1 on write always. Added a diagnostic entity to read that last register, which returns the last write action status information on read.
Updated docs.
> Fix update system time

- custom_components/solax_modbus/plugin_sofar.py
Closes #703 
Removing the following fields:
- Battery Active Control: Was not working and should never be changed. Disabling does not make sense as a battery in standby would no longer wake up
- Battery Minimum Capacity: Not working
- Battery Maximum Capacity: Not working
Later two points  have to be set with a huge set of other extremely critical registers. Will need to evaluate further, but it's very unlikely that the risk is worth adding these two capacity controls back. Therefore closing #703 for now.
> Removed non-functional Battery Control and Capacity controls

- custom_components/solax_modbus/__init__.py
When adding the Solax integration, it waited forever for HA to start.
Now it checks whether HA is already running and if so, the Modbus connection is established immediately,
otherwise it waits for the HA start.
> Fix adding Solax integration without HA restart

- custom_components/solax_modbus/plugin_sofar.py
Fixing these issues:
```
2024-03-16 18:44:47.405 WARNING (MainThread) [custom_components.solax_modbus.sensor] holding register already used: 0x104d bat_config_depth_of_discharge
2024-03-16 18:44:47.405 WARNING (MainThread) [custom_components.solax_modbus.sensor] holding register already used: 0x104e bat_config_end_of_discharge
2024-03-16 18:44:47.405 WARNING (MainThread) [custom_components.solax_modbus.sensor] holding register already used: 0x1055 bat_config_address_4
```
> Sofar: Remove duplicate registers

- custom_components/solax_modbus/plugin_solax_ev_charger.py
For unknown reason (bug of SolaX) input register 0x10 is reg 32 BIG_ENDIAN.
Fortunately there is holding register 0x619 with same meaning which is correct.
Better to use correct register than fixing non standard encoding.
Solves #805
> Moving "Charge added total" to HOLDIG reg 0x619.

- custom_components/solax_modbus/plugin_solis.py
43073 is a register containing multiple bit switches which control all kinds of things. One of those is the phase power control mode. With the default balanced output inverter will always output the same power on all phases. This leads to selling on some phases and buying on others. With unbalanced output the inverter power control logic manages each phase separately which is what you want if your utility measures and bills each phase separately.
Unfortunately I don't see how to add multiple toggles linked to one register so I just added the options to the select. If you see a cleaner approach please let me know.
Tested with Solis S6-EH3P10K-H-EU
> Support phase unbalanced output with Solis inverters

- custom_components/solax_modbus/plugin_solax.py
Added in the serial prefix for my X3-Hybrid-6 Solax inverter.
Should fix https://github.com/wills106/homeassistant-solax-modbus/issues/861.
> X3-Hybrid-6 exports 6kW max

- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/const.py
- custom_components/solax_modbus/number.py
- custom_components/solax_modbus/plugin_solinteg.py
- custom_components/solax_modbus/select.py
- custom_components/solax_modbus/sensor.py
I added the "scan_interval" option for each sensor.
I implemented everything, grouping by interval, etc.
Of course it doesn't really make sense with many groups.
When not defined (<=0), the default hub interval is used.
I'm using scan_interval = 3s for very fast updates (only the grid power, I intend to use it as feedback), 10s for a few fast updates (PV Voltage, Power, Battery Power).
Everything else is at default, 1min for me.
I hope someone else finds this useful...
I also have another plugin where I'm using this, it's quite basic at this time.
Gabriel
> add optional scan_interval for sensors

- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/config_flow.py
- custom_components/solax_modbus/const.py
- custom_components/solax_modbus/plugin_solinteg.py
- custom_components/solax_modbus/strings.json
- custom_components/solax_modbus/translations/en.json
- custom_components/solax_modbus/translations/fr.json
I saw you accepted my changes... 👍
But I wanted to play myself with different intervals, and I realized that modifying source is not convenient (especially for users); and a full HA restart is also not nice...
Therefore I did some refactoring moving from explicit scan_interval to scan_group, and added 3 configuration options (default, medium, fast).
This way we can assign sensors (descriptors) to groups, but the scan interval is now user configurable (defaults **not** changed)
I also applied some small code refactoring, read config directly in hub constructor instead of passing lots of parameters.
Please review...
> make scan_group configurable

- docs/sofar-faq.md
Added description of invalid return codes on write attempts, when using the LSE-3 logger and how to workaround this issue.
Close #843
> Update sofar-faq.md: Invalid return codes for write attempts using the LSE-3 logger.

- custom_components/solax_modbus/__init__.py
Since I wasn't able to write any values through the modbus connection, this fixed the issue for me and I can write all the values just fine now. 
According to the documentation of pymodbus, the client should be trying to reconnect automatically within the given timout:
The line await client.connect() connects to the device (or comm port), if this cannot connect successfully within the timeout it throws an exception. If connected successfully reconnecting later is handled automatically
This might be a quick fix, maybe there should be the asyncio lock applied in the for loop to keep the retry functionality?
> Fix: Modubus Client not connected error

- custom_components/solax_modbus/plugin_solax.py
At least for my X3 Ultra 15K (H3BD15) this scaling correktion is working i guess it will be the same for the other Ultras as well.
See my comment: https://github.com/wills106/homeassistant-solax-modbus/issues/998#issuecomment-2295229198
> Export control scaling for X3-Ultra

- custom_components/solax_modbus/__init__.py
The client connection happens later in `self.async_lowlevel_write_register` call, if the client is not connected already
Potentially resolves #993
> Remove unnecessary client connection in async_write_register

- custom_components/solax_modbus/__init__.py
method parameter is not supported by pymodbus, according to: https://pymodbus.readthedocs.io/en/latest/source/client.html#pymodbus.client.ModbusSerialClient
The right way to provide framer type is through `framer` parameter, but that one is RTU by default, so no need to explicitly specify it in the call
This should fix https://github.com/wills106/homeassistant-solax-modbus/issues/1008
> Fix ModbusSerialClient initialization: remove unsupported method

- custom_components/solax_modbus/plugin_growatt.py
Fixes: add “auto_block_ignore_readerror = True” to growatt_plugin (fixes #1022)
Adds:
EMS Discharging Rate
EMS Discharging Stop SOC
EMS Charging Rate
EMS Charging Stop SOC
EPS Switch (for MOD series)
Total Grid Export (for MOD series)
Removes:
"Battery First Maximum SOC"  & "Charger Upper SOC" (Replaced by EMS controls above) 
"Limit Grid Export" (Priority mode select) as this is not for changing run mode for TL-XH. 
"Total Load" as not for TL-XH
Comments out register 3000 for “Inverter State” and “Run mode” until issue is fixed #791
Corrects:
Typo in naming of: bettery_combined_power to battery_combined_power 
Battery Voltage change scale to match APX HV specs range 600-980V for system module 
Battery Current adds REGISTER_S16 to correct value.
> Growatt: Fix sensors unknown due to issue #791. Add EMS / Battery control and other fixes

- custom_components/solax_modbus/plugin_solis.py
Fixes to Solis value_function_timingmode(), value_function_timingmode2() & value_function_timingmode3() to reference the updated entity naming from 2024.08.14 for the Timed Charge / Discharge hours/minutes parameters. 
Closes #1028 based on my own testing with a Solis inverter.
> Fix for #1028 Solis button functions

- custom_components/solax_modbus/plugin_solax.py
Write register is diffent than read register and there was switched Enable/Disable mapping.
In fact it is incorrect also in SolaX modbus document v3.24 (latest I have).
> #924 Fixed value mapping "battery_to_ev_charger"

- custom_components/solax_modbus/__init__.py
Fixing bug where incorrect file content stops integration from loading.
I didn't know how it happend but I found my SolaX_data.json empty. It is not valid json causing crash.
Solution is smple re-save data with saveLocalData method.
Tested myself. Simple test is to delete content of file and restart integration.
> #1037 Detect incorrect local data file content

- custom_components/solax_modbus/plugin_growatt.py
Fix #1052 For Growatt MOD TL3-XH: 
Add EMS Discharging Stop SOC (on grid) from register 3067. It does requires newer firmware version. Tested with version "DN1.0/DNAA065101/ZBDB-0008".
> Fix #1052 For Growatt MOD TL3-XH

- custom_components/solax_modbus/plugin_sofar.py
Currently the value is interpreted as a string.
With this change it is detected as INT and is more useful.
By(t)e
> Add "state_class" to "battery_charge_cycle_*"

- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/config_flow.py
- custom_components/solax_modbus/const.py
- custom_components/solax_modbus/strings.json
- custom_components/solax_modbus/translations/de.json
Adds the possibility to attach to the homeassistant core ModbusHub as a third type of connection. This requires that the core Modbus module is properly configured and registers can be read from the SolaX Inverter via the core Modbus component. If selected only the name of the Modbus Hub has to be specified. At the moment the name has to be typed into the field. 
This pull request reflects the needs for  my personal setup. I do appriciate any feedback, discussion, suggestions, recommendations etc.  I will update given sufficient time and resources.
> enhanced SolaXModbusHub to utilize core ModbusHub connection

- custom_components/solax_modbus/plugin_solax.py
This PR contains:
- Adds the missing meter direction register definitions for GEN4 inverters 
- Adds meter direction logic to measured power to avoid incorrect calculations for meters configured with positive meter flow. This fixes a major issue with incorrect house load calculations when a meter is configured with positive meter flow
To accomplish this the `measured_power` register is imported a as `measured_power_raw`. A new computed function has been added as `value_function_measured_power` that applies the direction to the raw data. That way all computations that leverage measured power inherit the fix without additional code changes.
I have been able to test this fix on Solax X3 Hybrid G4 inverters.
> Solax Gen4 meter direction and core meter direction fix

- custom_components/solax_modbus/plugin_growatt.py
- custom_components/solax_modbus/sensor.py
Work around the register 3000 not being split up. Read out the value as internal and then use value_function to translate.
To fix #791
> Growatt: Fix run mode #791

- custom_components/solax_modbus/const.py
- custom_components/solax_modbus/plugin_growatt.py
Created a fresh PR instead of #1068.
Adds Time Slot 1, 2, 3 settings with Time Begin, Time End, Mode and Enabled for each of the three. 
Select entities and button "Update Time Slots" to write to inverter. Also added a "Clear Time Slots" if all 3 slots should be cleared. 
There are seperate sensor with added "read" in name, as it otherwise does not always write the new selected value and one have to wait 2 minutes before being able to validate that the settings was been written.  Only Time Slot 1 entities is shown by default.
Buttons:
Selects:
Read sensors:
> Growatt TL3-XH: add Time Slot 1,2,3 for priority setting

- custom_components/solax_modbus/plugin_growatt.py
For Growatt TL3-XH (GEN4): 
Depending on battery system, the scaling on battery voltage can be different. Default is set to 0.01 as per Growatt Modbus documentation. 
Scaling is determined by value_function_battery_voltage which uses BMS Monitoring Version (register 3096) to select if it should be 0.1 scaling. 
The APX HX system uses "ZECA" and we can add more when they are known.
> Growatt TL3-XH: Scale battery voltage depending on battery system

- custom_components/solax_modbus/plugin_solax_ev_charger.py
- because my EVC SN starts with "C3111"
I tested by directly modifying the line in my HA local installation. I can then finally add the EVC into HA. The sensors and controls are added correctly. See the screenshots.
> Adapt the check of Solax EVC type using the SN number

- custom_components/solax_modbus/plugin_solax.py
NB Tested only on G4, can someone please look into G5?
> Add entity Main Breaker Current Limit

- custom_components/solax_modbus/const.py
- custom_components/solax_modbus/manifest.json
- custom_components/solax_modbus/plugin_growatt.py
- Solved issue where the serial number read count is to large for the actual registers in function `async_read_serialnr`.
- Updated pymodbus to align with home assistants 25.1 version (thanks @Luflosi for the comment on the PR)
- Updated version so version could be released if needed.
- Updated functions `value_function_rtc_ymd` and `value_function_rtc` to handle years with 4 digits as well
> Growatt serial-no buffer overrun + manifest pymodbus

- custom_components/solax_modbus/__init__.py
Updated parameter indexes since they seems to become mandatory for pymodbus.
Still no rework for warning on BinaryPayloadDecoder, this still needs to be done, but then at least the code is working for now.
Next days I don't have a lot of time to work on this
> Issues after pymodbus updates

- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/manifest.json
- custom_components/solax_modbus/payload.py
Brought the source file payload from the pyModbus project to the application. Done since payload.py is deprecated from pyModbus and causes a lot of warnings in the home assistant log. To perform a rewrite of the logic more time is needed since it's a major rewrite since we should be able to easily split a multi fetched register (result)
> Added payload.py from pyModbus to application

- docs/sofar-faq.md
- docs/sofar-installation.md
Documented some common pitfalls, when using the LSE3 logger stick in the Sofar FAQ.
> FAQ: Common LSE-3 pitfalls

- custom_components/solax_modbus/plugin_sofar.py
the battery is displayed as 6% instead of 60%, for example
Pull is local tested
> BatteryPack SOC in preview entity Realtime Capacity is wrong

- docs/sofar-installation.md
Trying to fix the format to better work with ReadTheDocs and fixed some typos
> Fix Sofar installation to work better with ReadTheDocs

- custom_components/solax_modbus/plugin_alphaess.py
- custom_components/solax_modbus/plugin_growatt.py
- custom_components/solax_modbus/plugin_sofar.py
- custom_components/solax_modbus/plugin_sofar_old.py
- custom_components/solax_modbus/plugin_solax.py
- custom_components/solax_modbus/plugin_solax_a1j1.py
- custom_components/solax_modbus/plugin_solax_ev_charger.py
- custom_components/solax_modbus/plugin_solax_mega_forth.py
- custom_components/solax_modbus/plugin_solinteg.py
- custom_components/solax_modbus/plugin_solis.py
- custom_components/solax_modbus/plugin_solis_fb00.py
- custom_components/solax_modbus/plugin_solis_old.py
- custom_components/solax_modbus/plugin_srne.py
- custom_components/solax_modbus/plugin_swatten.py
- custom_components/solax_modbus/translations/nl.json
Removed the deprecation message from pyModbus by changing the include in plugins from the original pymodbus.payload to local payload module
Issue #1223
> Removed last deprecation message in plugins

- custom_components/solax_modbus/plugin_sofar.py
- After clarifying that the scale issues of Realtime Capacity was a firmware issue, bringing it back. If someone sees Realtime Capacity of more than 100%, a firmware update to the latest version is advised.
- After removing the battery class adding icons for Realtime Capacity and SOH:
- Removed entities that were commented out, but repeated again later.
> Sofar: Bring back Realtime Capacity. Cleanup device class and icons

- custom_components/solax_modbus/plugin_solax_ev_charger.py
Added the startnumber of the Serial for Solax X3-HAC-11.
So the three phase modell can be recognized too.
> Update plugin_solax_ev_charger.py for Solax X3-HAC-11

- custom_components/solax_modbus/plugin_growatt.py
For Growatt MOD inverters. Fix error message if time x entities is not enabled. 
Fix #1307
> Fix error message if time slot x entities is not enabled.

- custom_components/solax_modbus/__init__.py
This is minimal commit to skip faulty Modbus readings causing spikes in data.
There is bug in PyModbus (<3.8.6).
Modbus has no option to physically cancel operation. When Read request times out (logic cancel in code), but physical device responds later, there is "orphan" packet which can in some situation be falsely read by next transaction. 
Pymodbus<3.8.6 does not check TransactionID so is vulnerable to this error.
PyModbus is core HA library so it is not possible to upgrade it only for one integration. We have to wait till HA upgrades.
I picked up exact solution used in PyModbus 3.8.6. On data receive it should check Request.TransactionId==Response.TransactionId.
Have to use more low lever reading function to have access to response properties.
> Ignore faulty Modbus reading

- custom_components/solax_modbus/plugin_solax.py
Variable EXPORT_LIMIT_SCALE_EXCEPTIONS adapted to work with Solax X3-Ultra 25K where the serial number starts with "H3BF".
> Adapt EXPORT_LIMIT_SCALE_EXCEPTIONS for Solax X3-Ultra 25K

- custom_components/solax_modbus/__init__.py
Fixing bug in previous PR.
Only Modbus TCP uses TransactionID. It should not be used for RTU or Ascii.
Actually bug where overlapping transactions results in incorrect data is only possible on Modbus TCP.
For non-TCP framer, TransactionID in response is always 0. Added condition to filter RTU out.
> Fix Modbus RTU does not have transactionID

- custom_components/solax_modbus/plugin_solax.py
In commit fa92b3ec10066f4b0368dcb9dd2d4c3fa112fd19, the Gen5 SolaX hybrid inverters were changed to use a calculation for inverter power based on three registers for each of three phases. However this only works for the 3-phase X3-IES Gen5 inverters.
The X1-IES Gen5 inverter is single phase, and so still uses the same register 0x2 as the older generation hybrid inverters.
Here we restrict the new Gen5 calculated inverter power sensor entity to X3 devices, and add a new sensor entity for the X1 gen5 variants which reads the power directly from register 0x2.
This fixes the problem I mentioned in https://github.com/wills106/homeassistant-solax-modbus/issues/813#issuecomment-2958056642.
---
(* note: perhaps there is a way to use the existing gen4 sensor, but looking at the way the allowed …
> Correct Inverter Power for SolaX X1-IES Hybrid Gen5 Inverter

- custom_components/solax_modbus/plugin_solax.py
Added "PV Limit" entity for Solax X3 Gen2 MIC/PRO to limit the power of the inverter by limiting the dc side.
I added this entity in order to have the ability to limit a additional X3-PRO-12k which is working besides a X3-Hybrid-12k. The PRO does not have any meter or CT connected which is probably the reason why limiting the export power does not work on the PRO. With this entity i can limit the power of the PRO to a percentage of the power specified for the inverter e.g. a 10% limit means a power limit of 1200W for the 12k. After setting the limit it takes 1 to 2 minutes for the inverter to reach the limit.
Sources for this entity: https://www.photovoltaikforum.com/core/file-download/369195/ page 18 "PowerLimitsPercent" and https://ro.solaxpower.com/uploads/file/x3-pro-g2-user-manual-en. …
> Added PV Limit entity for Solax X3 Gen2 MIC/PRO

- custom_components/solax_modbus/button.py
The bug affected non-autorepeat  buttons that do a write_multi
Seems to have affected 
- sofar, 
- growatt
- solax rtc button
> correct bug #1473 and potential other errors introduced in latest version

- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/const.py
- custom_components/solax_modbus/plugin_solax.py
- custom_components/solax_modbus/sensor.py
EDITED
- implement copy of suggested #1440 issue  solution - thanks @gec75 
- reduce messages when inverter is offline or asleep issue 
- copy/implement #1474 do not poll registers that are disabled. Thanks @TonyMathiesen. If a  sensor is enabled, the read_block structure needs to be recomputed, this caused some significant code moves. It which seems to work now. 
Needs to be reviewed and tested further by developers of the scan_group mechanism. 
- set modbus RETRIES = 0 instead of 6 (did not make sense in my opinion as the polling loop will retry automatically) 
- make some code more readable
- suppress autorepeat writes when inverter is offline
- Some code (e.g. splitInBlocks) moved from sensor.py to __init__.py
- modify value_function_pv_power_total, so that it does not scan entire …
> issues #1440 #1473 #1482; dont poll disabled sensors, better handling of offline situations, multiple_scan_groups enhancement

- custom_components/solax_modbus/__init__.py
- custom_components/solax_modbus/number.py
- custom_components/solax_modbus/select.py
Use entity registry to determine if entity is enabled - testers or reviewers welcome
So that disabled entities are not polled anymore. 
Fixes issue #1494
Also contains PR #1500 fix by @rosenrot00
Thanks @thomas7475
After previous failed attempt, it would be good that users of different inverters test this first.
EDIT: seems to work now  - thanks again @thomas7475 and @rosenrot00
> use entity registry to determine if entity is enabled - fix issue #1496, contains 1500 

- custom_components/solax_modbus/plugin_solax.py
This adds the kW value to the inverter name if it has a H34 serial number. To my knowledge there is only integer values from 5-15kW. Please correct me if I'm wrong.
To my knowledge there are H34A/B/C/T with the same 5-15kW ranges. Please correct me if I'm wrong and we need to differentiate between the different types.
> Add kW value to Solax H34 inverter models

- custom_components/solax_modbus/plugin_solax.py
Prevents this error:
2025-08-05 22:41:00.328 WARNING (MainThread) [custom_components.solax_modbus.plugin_solax] SolaX: attempt to read serialnumber failed at 0x0 data: None Traceback (most recent call last):
File "/config/custom_components/solax_modbus/plugin_solax.py", line 72, in async_read_serialnr
if not inverter_data.isError():
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isError'
> Prevent crash from None serialnumber
